apiVersion: apps/v1
kind: Deployment
metadata:
  name: du-workload-{{.Replica}}
  annotations:
    # Disable CPU balance with CRIO
    irq-load-balancing.crio.io: "disable"
    cpu-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
  labels:
    group: load
    svc: du-workload-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: du-workload-{{.Replica}}
  template:
    metadata:
      labels:
        group: load
        name: du-workload-{{.Replica}}
    spec:
      runtimeClassName: performance-openshift-node-performance-profile
      containers:
        - image: "{{ .Image }}"
          imagePullPolicy: Always
          name: du-workload-{{.Replica}}
          # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
          resources:
            requests:
              cpu: 32000m
              memory: 1024M
              hugepages-1Gi: 16Gi
            limits:
              cpu: 32000m
              memory: 1024M
              hugepages-1Gi: 16Gi
          # securityContext:
          #   privileged: true
          env:
            - name: stress_cpu
              value: "32"
            - name: stress_vm
              value: "1"
            - name: stress_vm-bytes
              value: "512M"
          volumeMounts:
            - name: configmap-1
              mountPath: /var/configmap1
            - name: configmap-2
              mountPath: /var/configmap2
            - name: secret-1
              mountPath: /var/secret1
            - name: secret-2
              mountPath: /var/secret2
            - name: secret-3
              mountPath: /var/secret3
            - name: secret-4
              mountPath: /var/secret4
            - name: hugepage
              mountPath: /hugepages
      dnsPolicy: Default
      terminationGracePeriodSeconds: 1
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 900
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 900
      volumes:
        - name: configmap-1
          configMap:
            name: configmap1-{{.Replica}}
        - name: configmap-2
          configMap:
            name: configmap2-{{.Replica}}
        - name: secret-1
          secret:
            secretName: secret1-{{.Replica}}
        - name: secret-2
          secret:
            secretName: secret2-{{.Replica}}
        - name: secret-3
          secret:
            secretName: secret3-{{.Replica}}
        - name: secret-4
          secret:
            secretName: secret4-{{.Replica}}
        - name: hugepage
          emptyDir:
            medium: HugePages