kind: Deployment
apiVersion: apps/v1
metadata:
  name: curl-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        name: curl-{{.Replica}}
        redhat-best-practices-for-k8s.com/generic: target
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: curlapp
          image: "{{ .Image_curl }}"
          command: ["sleep", "inf"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: WEBSERVER_HOSTNAME
              value: webserver-{{.Replica}}
            - name: WEBSERVER_PORT
              value: "8080"
          volumeMounts:
            {{ range  $volume := .volumes }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.path }}
            {{ end }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          startupProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "curl ${WEBSERVER_HOSTNAME}:${WEBSERVER_PORT}"
            periodSeconds: 15
            timeoutSeconds: 1
            failureThreshold: 600
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "curl ${WEBSERVER_HOSTNAME}:${WEBSERVER_PORT}"
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
        - name: nginx
          image: "{{ .Image_nginx }}"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60
      restartPolicy: Always
      volumes:
        {{ range  $volume := .volumes }}
        - name: {{ $volume.name }}
          {{ if eq $volume.type "configMap" }}
          configMap:
            name: {{ $volume.name }}
          {{ else if eq $volume.type "secret" }}
          secret:
            secretName: {{ $volume.name }}
          {{ else if eq $volume.type "persistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ $volume.name }}
          {{ end }}
        {{ end }}
  replicas: 1
  selector:
    matchLabels:
      name: curl-{{.Replica}}
      redhat-best-practices-for-k8s.com/generic: target
  strategy:
    type: RollingUpdate
